pull_request_rules:
  - name: Automatic merge
    conditions:
      - "#approved-reviews-by>=1"
      - label=automerge
      - status-success=Lint
      - status-success=Typing Successful
      - status-success=Test Successful
      - status-success=Docker Test Successful
      - status-success=Windows Test Successful
      - status-success=MinGW
    actions:
      merge:
        method: merge
