name-template: "$NEXT_MINOR_VERSION"
tag-template: "$NEXT_MINOR_VERSION"
change-template: '- $TITLE #$NUMBER [@$AUTHOR]'

categories:
  - title: "Removals"
    label: "Removal"
  - title: "Deprecations"
    label: "Deprecation"
  - title: "Documentation"
    label: "Documentation"
  - title: "Dependencies"
    label: "Dependency"
  - title: "Testing"
    label: "Testing"
  - title: "Type hints"
    label: "Type hints"
  - title: "Other changes"

exclude-labels:
  - "changelog: skip"

template: |

  https://pillow.readthedocs.io/en/stable/releasenotes/$NEXT_MINOR_VERSION.html

  $CHANGES
