# Documentation: https://docs.codecov.io/docs/codecov-yaml

codecov:
  # Avoid "Missing base report" due to committing CHANGES.rst with "[CI skip]"
  # https://github.com/codecov/support/issues/363
  # https://docs.codecov.io/v4.3.6/docs/comparing-commits
  allow_coverage_offsets: true

  token: 6dafc396-e7f5-4221-a38a-8b07a49fbdae

comment: off
