version: 2

formats: [pdf]

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  jobs:
    post_checkout:
    - git remote add upstream https://github.com/python-pillow/Pillow.git # For forks
    - git fetch upstream --tags

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
