# Documentation: https://docs.codecov.com/docs/codecov-yaml

codecov:
  # Avoid "Missing base report" due to committing CHANGES.rst with "[CI skip]"
  # https://github.com/codecov/support/issues/363
  # https://docs.codecov.com/docs/comparing-commits
  allow_coverage_offsets: true

comment: false

coverage:
  status:
    project:
      default:
        threshold: 0.01%

# Matches 'omit:' in .coveragerc
ignore:
  - "Tests/bench_cffi_access.py"
  - "Tests/check_*.py"
  - "Tests/createfontdatachunk.py"
